name: nb-decomon-py3.8
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
      - kaggle
      - pandas
      - tensorboard>=2.13
      - jupyter-server-proxy
      - decomon==0.1.1
